// Content for the "Goodbye Ritual" free activity — Hebrew (RTL) and English (LTR).

const HE_GOODBYE = [
  { id: 'g1', t: 'חיבוק גדול וארוך' },
  { id: 'g2', t: 'הכיף-פייב שלנו' },
  { id: 'g3', t: 'נשיקת פרפר' },
  { id: 'g4', t: 'לב על היד' },
  { id: 'g5', t: 'שיר קטן שאנחנו שרים' },
  { id: 'other', t: 'משהו אחר', n: 'ספר/י לנו מה' },
];

const HE_HELP = [
  { id: 'h1', t: 'שיחת בוקר רגועה על מה שצפוי היום' },
  { id: 'h2', t: 'הצעצוע או החפץ הקטן שהוא/היא לוקח/ת איתו/ה' },
  { id: 'h3', t: 'תזכורת שאנחנו תמיד חוזרים' },
  { id: 'h4', t: 'לתת לו/לה זמן להיפרד בקצב שלו/שלה' },
  { id: 'h5', t: 'לא להימשך אם הוא/היא רוצה שנלך מהר' },
  { id: 'other', t: 'משהו אחר' },
];

const EN_GOODBYE = [
  { id: 'g1', t: 'A big, long hug' },
  { id: 'g2', t: 'Our special high-five' },
  { id: 'g3', t: 'A butterfly kiss' },
  { id: 'g4', t: 'A heart drawn on the hand' },
  { id: 'g5', t: 'A little song we sing' },
  { id: 'other', t: 'Something else', n: 'Tell us what' },
];

const EN_HELP = [
  { id: 'h1', t: 'A calm morning chat about what to expect today' },
  { id: 'h2', t: 'The small toy or object they bring along' },
  { id: 'h3', t: 'A reminder that we always come back' },
  { id: 'h4', t: 'Giving them time to say goodbye at their own pace' },
  { id: 'h5', t: "Not lingering if they'd rather we go quickly" },
  { id: 'other', t: 'Something else' },
];

export const GOODBYE_PARENT_LINES_EN = [
  { id: 'p1', t: "I'm saying goodbye now, and I'll come back to get you later." },
  { id: 'p2', t: "You are safe, loved, and ready." },
  { id: 'p3', t: "Even if it feels a little hard, you are not alone." },
  { id: 'p4', t: "I believe in you. You can do this." },
  { id: 'other', t: 'Write your own line' },
];

export const GOODBYE_CHILD_LINES_EN = [
  { id: 'c1', t: "I can do this." },
  { id: 'c2', t: "Mom or Dad always comes back." },
  { id: 'c3', t: "I am safe." },
  { id: 'c4', t: "I'll try, even if it feels a little hard." },
  { id: 'other', t: 'Write your own line' },
];

export const GOODBYE_RITUAL_CONTENT = {
  he: {
    s0: {
      h1: 'טקס פרידה קטן, שיהפוך לבוקר בטוח',
      lede: 'כמה דקות עכשיו, יוצרות טקס פרידה שהילד/ה שלכם יכיר וייקח איתו לגן או לבית הספר.',
      p1: 'פרידות בבוקר יכולות להיות רגע רגיש, גם לילדים וגם להורים. טקס קבוע, קצר וצפוי, עוזר לילד/ה לדעת בדיוק למה לצפות, ולהיפרד בביטחון.',
      p2: 'תוך כמה דקות תקבלו כרטיס פרידה אישי, מוכן להדפסה ולתלייה ליד הדלת או בתיק.',
      chips: ['לוקח כ-3 דקות', 'מתאים לכל גיל גן וכיתה א׳', 'ניתן להדפסה מיידית'],
      btn: 'בואו נתחיל ✨',
      resumeBtn: 'המשך מהיכן שהפסקתי',
      restartSmall: 'התחל/י מחדש',
    },
    navBack: '← חזרה',
    s1: {
      h2: 'קצת עליכם',
      sub: 'כדי שהטקס יתאים בול לילד/ה שלכם.',
      nameLabel: 'שם הילד/ה',
      namePh: 'איך קוראים לו/לה?',
      genderLabel: 'מגדר הילד/ה',
      genderAria: 'בחירת מגדר',
      genderBoy: 'ילד',
      genderGirl: 'ילדה',
      genderNeutral: 'מעדיפים לא לציין',
      parentLabel: 'מי נפרד/ת ממנו/ה בבוקר בדרך כלל?',
      parentAria: 'בחירת הורה',
      parentMom: 'אמא',
      parentDad: 'אבא',
      parentOther: 'אחד ההורים',
      next: 'המשך',
    },
    s2: {
      h2: 'איך אתם רגילים להיפרד?',
      sub: 'בחרו את הפעולה שהכי מתאימה, או תארו את שלכם.',
      otherPh: 'תארו את טקס הפרידה שלכם',
      tip: 'טקס פרידה קבוע וקצר עוזר לילדים לדעת למה לצפות, וזה מרגיע.',
      next: 'המשך',
    },
    s3: {
      h2: 'מה חשוב לכם להגיד ברגע הפרידה?',
      sub: 'המשפט הזה יופיע על הכרטיס, בדיוק כמו שהילד/ה ישמע/תשמע אותו מכם.',
      otherPh: 'כתבו את המשפט שלכם',
      tip: 'משפט קבוע וחוזר נותן לילד/ה עוגן להיאחז בו כל בוקר.',
      next: 'המשך',
    },
    s4: {
      titleDefault: 'מה חשוב שהוא/היא יגיד/תגיד לעצמו/ה?',
      titleWithName: (name) => `מה חשוב ש${name} יגיד/תגיד לעצמו/ה?`,
      sub: 'משפט קטן שהילד/ה יכול/ה לחזור עליו כשקצת קשה.',
      otherPh: 'כתבו משפט אחר',
      tip: 'משפט אישי, בגוף ראשון, הופך לכלי שהילד/ה יכול/ה להשתמש בו לבד.',
      next: 'המשך',
    },
    s5: {
      h2: 'מה הכי עוזר לו/לה בבוקר?',
      sub: 'אפשר לבחור כמה תשובות.',
      otherPh: 'משהו אחר שעוזר',
      tip: 'לדעת מה עוזר לילד/ה שלכם זה חצי מהדרך להפוך את הבוקר לקל יותר.',
      next: 'המשך',
    },
    s6: {
      h2: 'עוד כמה פרטים קטנים',
      sub: 'זה עוזר לילד/ה לדעת למה לצפות אחרי הפרידה.',
      pickupLabel: 'מי אוסף אותו/ה בסוף היום?',
      pickupPh: 'לדוגמה: אמא אוספת בסוף היום',
      pickupQuick: ['אמא אוספת', 'אבא אוסף', 'סבתא/סבא אוספים'],
      firstLabel: 'מה הדבר הראשון שתעשו ביחד כשתתראו?',
      firstPh: 'לדוגמה: נחבק חזק ונספר על היום',
      firstQuick: ['נחבק חזק', 'נלך הביתה ביחד', 'נאכל חטיף ונספר על היום'],
      next: 'המשך לסיכום',
    },
    s7: {
      eyebrow: 'טקס הפרידה של',
      sub: 'הדפיסו ותלו ליד הדלת, או קפלו ושימו בתיק',
      rowGoodbye: 'איך ניפרד',
      rowParentDefault: 'מה ההורה אומר/ת',
      rowChildDefault: 'מה אני אומר/ת לעצמי',
      rowHelp: 'מה עוזר',
      rowPickup: 'מי אוסף',
      rowFirst: 'הדבר הראשון שנעשה',
      warmStrong: 'זכרו:',
      warmText: 'טקס קבוע לא צריך להיות מושלם, הוא רק צריך להיות שלכם. ככל שתחזרו עליו יותר, כך הוא יהפוך לעוגן בטוח יותר.',
      howtoTitle: 'איך להשתמש בכרטיס',
      howtoItems: [
        'הדפיסו ותלו במקום שהילד/ה רואה בבוקר, ליד הדלת או בתיק.',
        'עברו יחד על השלבים כמה פעמים בבית, לפני שמנסים בפועל.',
        'שמרו על אותו סדר ואותן מילים כל בוקר, זה מה שיוצר את הביטחון.',
      ],
      btnPrint: '🖨️ הדפסה',
      btnSave: '💾 שמירה כקובץ',
      btnRestart: '🔄 התחלה מחדש',
      savetextAria: 'טקסט הכרטיס',
      btnCopy: 'העתקה',
      btnCopyDone: 'הועתק ✓',
      btnCopyManual: 'סמנו והעתיקו ידנית',
      btnCloseSave: 'סגירה',
      ctaText: 'רוצים סיפור אישי שממשיך לעזור ל ילד/ה שלכם להתמודד עם רגעים כאלה?',
      ctaLink: 'ליצירת סיפור אישי ←',
      optinHint: 'רוצים לקבל את הכרטיס למייל, או לשמוע כשיהיו עוד פעילויות כאלה בחינם?',
      optinPh: 'האימייל שלך',
      optinSubmit: 'שליחה',
      optinSkip: 'לא תודה, אולי בפעם אחרת',
      optinThanks: 'תודה! נעדכן אתכם 💌',
      disclaimer: 'הכרטיס נוצר במכשיר שלכם בלבד ולא נשמר אצלנו, אלא אם בחרתם להשאיר אימייל.',
    },
    fallback: '-',
    sumNameFallback: 'הילד/ה שלנו',
    stepLabel: (n, total) => `שלב ${n} מתוך ${total}`,
    GOODBYE: HE_GOODBYE,
    HELP: HE_HELP,
    parentOtherLabel: 'המשפט שכתבתם',
    childOtherLabel: 'המשפט שכתבתם',
    downloadFileName: 'טקס-פרידה.txt',
  },
  en: {
    s0: {
      h1: 'A tiny goodbye ritual that turns into a safe morning',
      lede: "A few minutes now can build a goodbye ritual your child will recognize and carry with them to daycare or school.",
      p1: "Morning goodbyes can feel like a sensitive moment, for kids and parents alike. A short, steady, predictable ritual helps a child know exactly what to expect, and to say goodbye feeling secure.",
      p2: "In just a few minutes you'll get a personalized goodbye card, ready to print and hang by the door or tuck into a bag.",
      chips: ['Takes about 3 minutes', 'Works for preschool through 1st grade', 'Print it right away'],
      btn: "Let's start ✨",
      resumeBtn: 'Continue where I left off',
      restartSmall: 'Start over',
    },
    navBack: '← Back',
    s1: {
      h2: 'A little about you',
      sub: "So the ritual fits your child perfectly.",
      nameLabel: "Child's name",
      namePh: "What's their name?",
      genderLabel: "Child's gender",
      genderAria: 'Select gender',
      genderBoy: 'Boy',
      genderGirl: 'Girl',
      genderNeutral: 'Prefer not to say',
      parentLabel: 'Who usually says goodbye in the morning?',
      parentAria: 'Select parent',
      parentMom: 'Mom',
      parentDad: 'Dad',
      parentOther: 'One of the parents',
      next: 'Continue',
    },
    s2: {
      h2: 'How do you usually say goodbye?',
      sub: 'Pick the one that fits best, or describe your own.',
      otherPh: 'Describe your goodbye ritual',
      tip: 'A short, consistent goodbye ritual helps kids know what to expect, and that is what makes it calming.',
      next: 'Continue',
    },
    s3: {
      h2: 'What matters most for you to say at goodbye?',
      sub: "This line will appear on the card, exactly as your child hears it from you.",
      otherPh: 'Write your own line',
      tip: 'A steady, repeated line gives your child something to hold onto every morning.',
      next: 'Continue',
    },
    s4: {
      titleDefault: 'What matters most for them to say to themselves?',
      titleWithName: (name) => `What matters most for ${name} to say to themselves?`,
      sub: 'A short line your child can repeat when things feel a little hard.',
      otherPh: 'Write a different line',
      tip: 'A personal, first-person line becomes a tool your child can use on their own.',
      next: 'Continue',
    },
    s5: {
      h2: 'What helps them most in the morning?',
      sub: 'You can choose more than one.',
      otherPh: 'Something else that helps',
      tip: 'Knowing what helps your child is half the way to an easier morning.',
      next: 'Continue',
    },
    s6: {
      h2: 'A few more small details',
      sub: 'This helps your child know what to expect after goodbye.',
      pickupLabel: 'Who picks them up at the end of the day?',
      pickupPh: 'For example: Mom picks up at the end of the day',
      pickupQuick: ['Mom picks up', 'Dad picks up', 'Grandma or Grandpa pick up'],
      firstLabel: 'What is the first thing you do together when you meet again?',
      firstPh: 'For example: A big hug and tell each other about our day',
      firstQuick: ['A big hug', 'Walk home together', 'A snack and hear about the day'],
      next: 'Continue to summary',
    },
    s7: {
      eyebrow: "Goodbye ritual for",
      sub: 'Print and hang by the door, or fold and tuck into a bag',
      rowGoodbye: 'How we say goodbye',
      rowParentDefault: 'What the parent says',
      rowChildDefault: 'What I say to myself',
      rowHelp: 'What helps',
      rowPickup: 'Who picks up',
      rowFirst: 'The first thing we do',
      warmStrong: 'Remember:',
      warmText: "A ritual doesn't need to be perfect, it just needs to be yours. The more you repeat it, the safer an anchor it becomes.",
      howtoTitle: 'How to use this card',
      howtoItems: [
        'Print it and hang it somewhere your child sees in the morning, by the door or inside their bag.',
        'Walk through the steps together a few times at home before trying it for real.',
        'Keep the same order and the same words every morning, that is what builds the sense of safety.',
      ],
      btnPrint: '🖨️ Print',
      btnSave: '💾 Save as a file',
      btnRestart: '🔄 Start over',
      savetextAria: 'Card text',
      btnCopy: 'Copy',
      btnCopyDone: 'Copied ✓',
      btnCopyManual: 'Select and copy manually',
      btnCloseSave: 'Close',
      ctaText: 'Want a personalized story that keeps helping your child through moments like this?',
      ctaLink: 'Create a personal story ←',
      optinHint: 'Want the card emailed to you, or to hear when we release more free activities?',
      optinPh: 'Your email',
      optinSubmit: 'Send',
      optinSkip: 'No thanks, maybe next time',
      optinThanks: "Thank you! We'll be in touch 💌",
      disclaimer: 'The card is created only on your device and is not saved by us, unless you choose to leave an email.',
    },
    fallback: '-',
    sumNameFallback: 'our child',
    stepLabel: (n, total) => `Step ${n} of ${total}`,
    GOODBYE: EN_GOODBYE,
    HELP: EN_HELP,
    parentOtherLabel: 'The line you wrote',
    childOtherLabel: 'The line you wrote',
    downloadFileName: 'goodbye-ritual.txt',
  },
};