// Content for "A Little Heart from Home" free activity — Hebrew (RTL) and English (LTR).

const SYMS_HE = { heart: 'לב', star: 'כוכב', sun: 'שמש', rainbow: 'קשת', house: 'בית', cloud: 'ענן', moon: 'ירח', flower: 'פרח', kite: 'עפיפון', feather: 'נוצה', hands: 'ידיים', spark: 'ניצוץ' };
const SYMS_EN = { heart: 'Heart', star: 'Star', sun: 'Sun', rainbow: 'Rainbow', house: 'House', cloud: 'Cloud', moon: 'Moon', flower: 'Flower', kite: 'Kite', feather: 'Feather', hands: 'Hands', spark: 'Spark' };

export const LITTLE_HEART_CONTENT = {
  he: {
    stepLabel: (n, total) => `שלב ${n} מתוך ${total}`,
    navContinueDefault: 'המשך',
    navBack: 'חזרה',
    downloadTitle: (name) => `לב קטן מהבית${name ? ' - ' + name : ''}`,
    downloadFileName: (name) => `לב-קטן-מהבית${name ? '-' + name : ''}.html`,
    formats: [
      { id: 'double', t: 'כרטיס מקופל דו-צדדי', d: 'הודעה בחוץ, פתק אישי בפנים', unit: 'מ״מ' },
      { id: 'single', t: 'כרטיס חד-צדדי', d: 'קטן ופשוט לשים בתיק', unit: 'מ״מ' },
      { id: 'folded', t: 'כרטיס גדול מתקפל', d: 'מקום נוסף להודעה ארוכה יותר', unit: 'מ״מ' },
      { id: 'coloring', t: 'דף צביעה', d: 'הילד/ה יכול/ה לצייר ולצבוע בעצמו/ה', unit: 'מ״מ' },
    ],
    card: {
      backPrompt: 'משהו קטן שיעזור היום',
      defaultAction: 'קחו נשימה עמוקה, אתם מסוגלים',
      nameOf: (name) => `בשביל ${name}`,
      defaultName: 'בשביל הילד/ה שלנו',
      coloringPrompt: 'מקום לצייר ולצבוע',
      coloringSign: (action) => `${action}`,
      storagePrefix: 'לשמור ב: ',
      openPrefix: 'לפתוח: ',
      helpableInline: (action) => action,
    },
    keepsakes: [
      { id: 'letter', t: 'מכתב קטן מההורה', d: 'כמה משפטים חמים בכתב יד שלכם' },
      { id: 'courage', t: 'משפט אומץ', d: 'משפט קצר שהילד/ה יכול/ה לחזור עליו' },
      { id: 'photo', t: 'תמונה משפחתית', d: 'תמונה שתלווה אותו/ה לאורך היום' },
      { id: 'drawing', t: 'ציור קטן', d: 'ציור שלכם, של הילד/ה, או שניהם ביחד' },
    ],
    themes: ['אהבה ותמיכה', 'אומץ וביטחון', 'חיבור למשפחה', 'שמחה וכיף', 'גאווה בו/בה', 'רוגע ובטחון'],
    actions: ['לחבק חזק בבוקר', 'להזכיר שנחזור', 'לתת רגע שקט לפני שנפרדים', 'לספר מה יקרה במהלך היום', 'לא למהר, לתת לו/לה זמן'],
    places: ['בתיק הגן/בית הספר', 'בכיס המעיל', 'בקופסת האוכל', 'מתחת לכרית', 'בארנק הקטן שלו/שלה', 'על שולחן הלימוד'],
    styles: [
      { id: 'soft', t: 'חם ורך', d: 'צבעים חמים, עיצוב חמים ומזמין' },
      { id: 'quiet', t: 'נקי ושקט', d: 'עיצוב מינימליסטי ורגוע' },
      { id: 'grown', t: 'קצת יותר "גדול"', d: 'עיצוב שמרגיש קצת יותר בוגר' },
    ],
    symbols: SYMS_HE,
    moments: ['כשמתעוררים בבוקר', 'ברכב בדרך לגן', 'כשמגיעים לכיתה', 'בהפסקה', 'לפני השינה'],
    courage: [
      'אני אמיץ/ה, גם כשקצת מפחיד.',
      'אני יכול/ה להתמודד עם דברים חדשים.',
      'גם אם קשה, אני מנסה.',
      'אני בטוח/ה בעצמי/עצמי.',
      'אני לא לבד, גם כשההורים לא לידי.',
    ],
    photoLines: [
      'אנחנו איתך גם כשאנחנו לא לידך.',
      'תמיד נחזור לקחת אותך.',
      'אנחנו כל כך אוהבים אותך.',
      'תראה/י לנו את היום המדהים שלך כשנתראה.',
    ],
    letterStarters: (name) => [
      `${name || 'ילד/ה יקר/ה'} שלי,`,
      'אני כל כך גאה/ה בך כי',
      'אני רוצה שתדע/י ש',
      'כשתתגעגע/י אלינו, תזכור/י ש',
    ],
    letterSamples: (name) => [
      `${name || 'ילד/ה יקר/ה'} שלי, אני כל כך גאה בך על כמה שאתה/את אמיץ/ה. אני איתך תמיד, גם כשאני לא לידך. אני אוהב/ת אותך עד השמיים ובחזרה.`,
      `בוקר טוב אהוב/ה שלי! היום הולך להיות יום מדהים. תזכור/י שאני חושב/ת עליך כל הזמן, ותמיד אחזור לקחת אותך. אני כל כך גאה בך.`,
    ],
    screens: {
      s0: {
        title: 'לב קטן מהבית',
        lede: 'צרו כרטיס אישי, חם וקטן, שהילד/ה שלכם ייקח/תיקח איתו/ה במהלך היום, כדי להרגיש קרוב/ה אליכם גם כשאתם לא שם.',
        note: 'זו פעילות קצרה וחינמית, שנוצרת רק במכשיר שלכם.',
        hint: 'לוקח כ-4 דקות',
        cta: 'בואו ניצור אחד ✨',
        foot: 'הכרטיס לא נשמר אצלנו, אלא אם תבחרו לשתף אימייל בסוף.',
      },
      s1: { eyebrow: 'שלב 1', h2: 'בשביל מי הכרטיס?', hint: 'זה יעזור לנו להתאים את הכרטיס בול.', label: 'שם הילד/ה', ph: 'איך קוראים לו/לה?' },
      s2: { eyebrow: 'שלב 2', h2: 'איזה סוג כרטיס תרצו ליצור?', hint: 'כל אחד מהם דרך אחרת להעביר חום ואהבה.' },
      s3: { eyebrow: 'שלב 3', h2: (name) => `מה חשוב לכם להעביר ל${name || 'ילד/ה שלכם'}?`, hint: 'בחרו עד שני נושאים.', otherLabel: 'נושא אחר', otherPh: 'תארו במילים שלכם', twoNote: 'בחרתם שני נושאים, מעולה!' },
      s4: { eyebrow: 'שלב 4', signLabel: 'איך תרצו לחתום?', signPh: 'לדוגמה: אמא ואבא, שאוהבים אותך' , warn: 'ההודעה ארוכה, ייתכן שנצטרך להקטין את הגופן כדי שתתאים לכרטיס.' },
      s5: { eyebrow: 'שלב 5', h2: 'בחרו סמל לכרטיס', hint: 'סמל שיעטר את הכרטיס.', secondaryHint: 'רוצים סמל שני קטן?', secondaryNone: 'בלי סמל שני' },
      s6: { eyebrow: 'שלב 6', h2: 'מה יעזור לו/לה במיוחד היום?', hint: 'נוסיף את זה לצד השני של הכרטיס.', otherLabel: 'עוד משהו שעוזר', otherPh: 'כתבו את זה' },
      s7: { eyebrow: 'שלב 7', h2: 'איפה הכרטיס יישמר?', hint: 'ככה הוא/היא ידע/תדע איפה לחפש אותו.', otherLabel: 'מקום אחר', otherPh: 'איפה?', note: 'אפשר לבחור כמה מקומות ולהדפיס עותקים נוספים בסוף.' },
      s8: { eyebrow: 'שלב 8', h2: 'איזה עיצוב הכי מתאים?', hint: 'בחרו את הסגנון שהכי מדבר אליכם.' },
      s9: { eyebrow: 'שלב 9', h2: 'איזה פורמט תרצו להדפיס?', hint: 'אפשר לבחור כמה, ולהדפיס את כולם ביחד.', warn: 'ההודעה ארוכה יחסית, כרטיס מתקפל ייתן יותר מקום.' },
      s10: { eyebrow: 'שלב 10', h2: (name) => `הכרטיס של ${name || 'הילד/ה שלכם'} מוכן!`, hint: 'ככה הוא ייראה. אפשר עדיין לשנות דברים.', chipMsg: 'שינוי ההודעה', chipStyle: 'שינוי העיצוב', chipSymbol: 'שינוי הסמל', nextLabel: 'המשך' },
      s11: { eyebrow: 'שלב 11', h2: 'מתי כדאי לפתוח את הכרטיס?', p: 'זה יכול לעזור לילד/ה לדעת מתי הרגע הכי טוב לפתוח את הכרטיס וליהנות ממנו.', promptLabel: 'בחרו רגע', otherLabel: 'רגע אחר', otherPh: 'מתי?', includeLabel: 'הוסיפו את הרגע הזה לכרטיס', nextLabel: 'המשך' },
      s12: {
        eyebrow: 'מוכן!', h2: (name) => `הכרטיס של ${name || 'הילד/ה שלכם'} מוכן להדפסה`, hint: 'הדפיסו אותו כמות שרוצים, או שמרו אותו כקובץ.',
        copiesLabel: 'כמה עותקים להדפיס?', copiesHint: 'טוב לשמור עותק גם בבית וגם בתיק.',
        printBtn: '🖨️ הדפסה', downloadBtn: 'שמירה כקובץ', imageBtn: 'שמירה כתמונה', changeMsg: 'שינוי ההודעה', changeDesign: 'שינוי העיצוב', resetBtn: 'התחלה מחדש',
        privacyNote: 'התמונה או הציור שהעליתם נשמרים רק במכשיר שלכם ולא נשלחים אלינו.',
        deleteBtn: 'מחיקה',
        ctaTitle: 'רוצים עוד?', ctaText: 'סיפור אישי יכול להמשיך את התמיכה הזו לאורך זמן, ולעזור לילד/ה שלכם להתמודד עם רגעים דומים.', ctaBtn: 'ליצירת סיפור אישי ←',
        leadHint: 'רוצים לקבל את הכרטיס למייל, או לשמוע כשיהיו עוד פעילויות כאלה בחינם?', leadPh: 'האימייל שלך', leadSubmit: 'שליחה', leadSkip: 'לא תודה', leadThanks: 'תודה! נעדכן אתכם 💌',
        foot: 'הכרטיס נוצר במכשיר שלכם בלבד.',
      },
    },
    letterBuilder: { h2: 'כתבו מכתב קטן', hint: 'כמה משפטים חמים, בדיוק כמו שהייתם אומרים בעל פה.', startersLabel: 'עזרה בהתחלה', letterLabel: 'המכתב שלכם', letterPh: 'התחילו לכתוב כאן...', words: (w, c) => `${w} מילים, ${c} תווים`, sampleLabel: 'או בחרו דוגמה מוכנה' },
    courageBuilder: { h2: 'בחרו משפט אומץ', hint: 'משפט קצר שהילד/ה יוכל/תוכל לחזור עליו בעצמו/ה.', customLabel: 'או כתבו משפט משלכם', customPh: 'כתבו כאן', secondLabel: 'שורה נוספת (לא חובה)', secondPh: 'משהו קטן נוסף' },
    photoBuilder: { h2: 'העלו תמונה משפחתית', hint: 'תמונה שתלווה את הילד/ה במהלך היום.', changeBtn: 'החלפת תמונה', deleteBtn: 'מחיקה', dropHint: 'גררו תמונה לכאן או', chooseBtn: 'בחירת תמונה', chooseAria: 'בחירת קובץ תמונה', note: 'התמונה נשמרת רק במכשיר שלכם.', msgLabel: 'הודעה קצרה לצד התמונה', msgPh: 'כתבו הודעה קצרה' },
    drawingBuilder: { h2: 'הוסיפו ציור', hint: 'אפשר לצייר כאן, להעלות ציור קיים, או להשאיר את הכרטיס נקי לצביעה.', modeCanvas: 'ציור כאן', modeUpload: 'העלאת ציור', modeBlank: 'להשאיר ריק', canvasAria: 'לוח ציור', toolPen: 'עיפרון', toolEraser: 'מחק', undoBtn: 'ביטול', clearBtn: 'ניקוי', deleteBtn: 'מחיקה', uploadHint: 'גררו ציור לכאן או', chooseBtn: 'בחירת קובץ', blankNote: 'הכרטיס יישאר ריק כדי שהילד/ה יוכל/תוכל לצייר עליו בעצמו/ה.', note: 'הציור נשמר רק במכשיר שלכם.', msgLabel: 'הודעה קצרה לצד הציור', msgPh: 'כתבו הודעה קצרה' },
    modal: {
      imageTitle: 'שמירה כתמונה', imageText: 'נפתח את חלון ההדפסה, שם תוכלו לבחור "שמירה כ-PDF" כדי לקבל תמונה.', imageBtn: 'להמשיך להדפסה',
      downloadTitle: 'לא הצלחנו לשמור קובץ', downloadText: 'נסו להדפיס ולשמור כ-PDF במקום.', downloadBtn: 'הבנתי',
      resetTitle: 'להתחיל מחדש?', resetText: 'כל מה שמילאתם יימחק.', resetYes: 'כן, להתחיל מחדש', resetNo: 'לא, להישאר כאן',
    },
  },
  en: {
    stepLabel: (n, total) => `Step ${n} of ${total}`,
    navContinueDefault: 'Continue',
    navBack: 'Back',
    downloadTitle: (name) => `A Little Heart from Home${name ? ' - ' + name : ''}`,
    downloadFileName: (name) => `little-heart-from-home${name ? '-' + name : ''}.html`,
    formats: [
      { id: 'double', t: 'Folded double-sided card', d: 'A message outside, a private note inside', unit: 'mm' },
      { id: 'single', t: 'Single-sided card', d: 'Small and simple to tuck in a bag', unit: 'mm' },
      { id: 'folded', t: 'Large folded card', d: 'Extra room for a longer message', unit: 'mm' },
      { id: 'coloring', t: 'Coloring page', d: 'Your child can draw and color it themselves', unit: 'mm' },
    ],
    card: {
      backPrompt: 'One small thing to help today',
      defaultAction: 'Take a deep breath, you can do this',
      nameOf: (name) => `For ${name}`,
      defaultName: 'For our child',
      coloringPrompt: 'A space to draw and color',
      coloringSign: (action) => `${action}`,
      storagePrefix: 'Keep it in: ',
      openPrefix: 'Open at: ',
      helpableInline: (action) => action,
    },
    keepsakes: [
      { id: 'letter', t: 'A short letter from a parent', d: 'A few warm sentences in your own words' },
      { id: 'courage', t: 'A courage sentence', d: 'A short line your child can repeat to themselves' },
      { id: 'photo', t: 'A family photo', d: 'A photo to keep them company through the day' },
      { id: 'drawing', t: 'A small drawing', d: 'Your drawing, your child\u2019s, or one you make together' },
    ],
    themes: ['Love and support', 'Courage and confidence', 'Family connection', 'Joy and fun', 'How proud we are of them', 'Calm and reassurance'],
    actions: ['A big hug in the morning', 'Reminding them we always come back', 'A quiet moment before saying goodbye', 'Telling them what to expect today', 'Not rushing, giving them their own pace'],
    places: ['In the daycare or school bag', 'In their coat pocket', 'In the lunchbox', 'Under the pillow', 'In their little wallet', 'On the desk'],
    styles: [
      { id: 'soft', t: 'Warm and soft', d: 'Warm colors, a cozy, inviting design' },
      { id: 'quiet', t: 'Clean and quiet', d: 'A minimal, calm design' },
      { id: 'grown', t: 'A bit more "grown up"', d: 'A design that feels a little more mature' },
    ],
    symbols: SYMS_EN,
    moments: ['When they wake up in the morning', 'In the car on the way', 'When they get to class', 'At recess', 'Before bedtime'],
    courage: [
      "I am brave, even when things feel a little scary.",
      "I can handle new things.",
      "Even when it's hard, I try.",
      "I believe in myself.",
      "I am never alone, even when my parents aren't right next to me.",
    ],
    photoLines: [
      "We are with you even when we're not right beside you.",
      "We will always come back for you.",
      "We love you so much.",
      "Tell us all about your amazing day when we see you.",
    ],
    letterStarters: (name) => [
      `My dear ${name || 'little one'},`,
      "I am so proud of you because",
      "I want you to know that",
      "Whenever you miss us, remember that",
    ],
    letterSamples: (name) => [
      `My dear ${name || 'little one'}, I am so proud of how brave you are. I am with you always, even when I'm not right beside you. I love you to the moon and back.`,
      `Good morning, my love! Today is going to be a wonderful day. Remember that I'm thinking of you all the time, and I will always come back for you. I am so proud of you.`,
    ],
    screens: {
      s0: {
        title: 'A Little Heart from Home',
        lede: "Create a small, personal, warm card your child can carry with them through the day, to feel close to you even when you're not there.",
        note: 'This is a short, free activity, created only on your device.',
        hint: 'Takes about 4 minutes',
        cta: "Let's create one ✨",
        foot: 'The card is not saved by us, unless you choose to share your email at the end.',
      },
      s1: { eyebrow: 'Step 1', h2: 'Who is this card for?', hint: "This helps us make the card just right.", label: "Child's name", ph: "What's their name?" },
      s2: { eyebrow: 'Step 2', h2: 'What kind of card would you like to create?', hint: 'Each one is a different way to share warmth and love.' },
      s3: { eyebrow: 'Step 3', h2: (name) => `What matters most for you to share with ${name || 'your child'}?`, hint: 'Choose up to two themes.', otherLabel: 'A different theme', otherPh: 'Describe it in your own words', twoNote: "You've picked two themes, great!" },
      s4: { eyebrow: 'Step 4', signLabel: 'How would you like to sign it?', signPh: 'For example: Mom and Dad, who love you', warn: "The message is a bit long, we may need to shrink the font so it fits the card." },
      s5: { eyebrow: 'Step 5', h2: 'Choose a symbol for the card', hint: 'A symbol to decorate the card.', secondaryHint: 'Want a small second symbol?', secondaryNone: 'No second symbol' },
      s6: { eyebrow: 'Step 6', h2: 'What helps them most today?', hint: "We'll add this to the other side of the card.", otherLabel: 'Something else that helps', otherPh: 'Write it here' },
      s7: { eyebrow: 'Step 7', h2: 'Where will the card be kept?', hint: 'This helps them know where to look for it.', otherLabel: 'A different spot', otherPh: 'Where?', note: 'You can choose more than one spot and print extra copies at the end.' },
      s8: { eyebrow: 'Step 8', h2: 'Which design feels right?', hint: 'Pick the style that speaks to you most.' },
      s9: { eyebrow: 'Step 9', h2: 'Which format would you like to print?', hint: 'You can pick more than one, and print them all together.', warn: 'The message is fairly long, a folded card will give you more room.' },
      s10: { eyebrow: 'Step 10', h2: (name) => `${name || "Your child"}'s card is ready!`, hint: "Here's how it looks. You can still change things.", chipMsg: 'Change the message', chipStyle: 'Change the design', chipSymbol: 'Change the symbol', nextLabel: 'Continue' },
      s11: { eyebrow: 'Step 11', h2: 'When should the card be opened?', p: 'This can help your child know the best moment to open and enjoy the card.', promptLabel: 'Choose a moment', otherLabel: 'A different moment', otherPh: 'When?', includeLabel: 'Add this moment to the card', nextLabel: 'Continue' },
      s12: {
        eyebrow: 'All set!', h2: (name) => `${name || "Your child"}'s card is ready to print`, hint: 'Print as many copies as you like, or save it as a file.',
        copiesLabel: 'How many copies to print?', copiesHint: "It's good to keep one at home and one in the bag.",
        printBtn: '🖨️ Print', downloadBtn: 'Save as a file', imageBtn: 'Save as an image', changeMsg: 'Change the message', changeDesign: 'Change the design', resetBtn: 'Start over',
        privacyNote: "The photo or drawing you uploaded is saved only on your device and is never sent to us.",
        deleteBtn: 'Delete',
        ctaTitle: 'Want more?', ctaText: 'A personalized story can carry this support further, helping your child through similar moments.', ctaBtn: 'Create a personal story ←',
        leadHint: 'Want the card emailed to you, or to hear when we release more free activities?', leadPh: 'Your email', leadSubmit: 'Send', leadSkip: 'No thanks', leadThanks: "Thank you! We'll be in touch 💌",
        foot: 'The card is created only on your device.',
      },
    },
    letterBuilder: { h2: 'Write a short letter', hint: 'A few warm sentences, exactly like you would say out loud.', startersLabel: 'Need a starting point', letterLabel: 'Your letter', letterPh: 'Start writing here...', words: (w, c) => `${w} words, ${c} characters`, sampleLabel: 'Or choose a ready-made example' },
    courageBuilder: { h2: 'Choose a courage sentence', hint: 'A short line your child can repeat to themselves.', customLabel: 'Or write your own line', customPh: 'Write it here', secondLabel: 'An extra line (optional)', secondPh: 'One more small thing' },
    photoBuilder: { h2: 'Upload a family photo', hint: 'A photo to keep your child company through the day.', changeBtn: 'Change photo', deleteBtn: 'Delete', dropHint: 'Drop a photo here or', chooseBtn: 'Choose photo', chooseAria: 'Choose an image file', note: 'The photo is saved only on your device.', msgLabel: 'A short message beside the photo', msgPh: 'Write a short message' },
    drawingBuilder: { h2: 'Add a drawing', hint: 'You can draw here, upload an existing drawing, or leave the card blank to color later.', modeCanvas: 'Draw here', modeUpload: 'Upload a drawing', modeBlank: 'Leave it blank', canvasAria: 'Drawing canvas', toolPen: 'Pen', toolEraser: 'Eraser', undoBtn: 'Undo', clearBtn: 'Clear', deleteBtn: 'Delete', uploadHint: 'Drop a drawing here or', chooseBtn: 'Choose a file', blankNote: 'The card will stay blank so your child can draw on it themselves.', note: 'The drawing is saved only on your device.', msgLabel: 'A short message beside the drawing', msgPh: 'Write a short message' },
    modal: {
      imageTitle: 'Save as an image', imageText: 'This opens the print window, where you can choose "Save as PDF" to get an image.', imageBtn: 'Continue to print',
      downloadTitle: "We couldn't save the file", downloadText: 'Try printing and saving as a PDF instead.', downloadBtn: 'Got it',
      resetTitle: 'Start over?', resetText: 'Everything you filled in will be cleared.', resetYes: 'Yes, start over', resetNo: 'No, stay here',
    },
  },
};