// Content for the "My Morning and Evening" routine board activity — Hebrew (RTL) and English (LTR).

const MORNING_HE = [
  { id: 'wake', t: 'להתעורר ולקום מהמיטה', i: 'sun' },
  { id: 'toilet', t: 'שירותים', i: 'toilet' },
  { id: 'wash', t: 'לשטוף פנים', i: 'drop' },
  { id: 'teeth', t: 'לצחצח שיניים', i: 'tooth' },
  { id: 'dress', t: 'להתלבש', i: 'shirt' },
  { id: 'hair', t: 'לסדר שיער', i: 'comb' },
  { id: 'breakfast', t: 'לאכול ארוחת בוקר', i: 'bowl' },
  { id: 'lunchpack', t: 'לקחת כריך וקופסת אוכל', i: 'lunchbox' },
  { id: 'bottle', t: 'למלא בקבוק מים', i: 'bottle' },
  { id: 'bag', t: 'לארוז תיק', i: 'backpack' },
  { id: 'shoes', t: 'לנעול נעליים', i: 'shoe' },
  { id: 'goodbye', t: 'להיפרד וללכת', i: 'door' },
];

const EVENING_HE = [
  { id: 'home', t: 'לחזור הביתה', i: 'home' },
  { id: 'unpack', t: 'לפרוק תיק', i: 'backpack' },
  { id: 'homework', t: 'שיעורי בית', i: 'pencil' },
  { id: 'play', t: 'זמן משחק', i: 'blocks' },
  { id: 'dinner', t: 'ארוחת ערב', i: 'dinner' },
  { id: 'bath', t: 'מקלחת או אמבטיה', i: 'shower' },
  { id: 'pajamas', t: 'ללבוש פיג׳מה', i: 'pajama' },
  { id: 'teeth2', t: 'לצחצח שיניים', i: 'tooth' },
  { id: 'tomorrow', t: 'להכין בגדים למחר', i: 'hanger' },
  { id: 'bagready', t: 'להכין תיק למחר', i: 'box' },
  { id: 'screenoff', t: 'לכבות מסכים', i: 'screenoff' },
  { id: 'story', t: 'סיפור לפני השינה', i: 'book' },
  { id: 'chat', t: 'שיחה קטנה על היום', i: 'chat' },
  { id: 'goodnight', t: 'חיבוק ולילה טוב', i: 'heart' },
  { id: 'sleep', t: 'לישון', i: 'bed' },
];

const MORNING_EN = [
  { id: 'wake', t: 'Wake up and get out of bed', i: 'sun' },
  { id: 'toilet', t: 'Bathroom', i: 'toilet' },
  { id: 'wash', t: 'Wash face', i: 'drop' },
  { id: 'teeth', t: 'Brush teeth', i: 'tooth' },
  { id: 'dress', t: 'Get dressed', i: 'shirt' },
  { id: 'hair', t: 'Do hair', i: 'comb' },
  { id: 'breakfast', t: 'Eat breakfast', i: 'bowl' },
  { id: 'lunchpack', t: 'Pack a sandwich and lunchbox', i: 'lunchbox' },
  { id: 'bottle', t: 'Fill water bottle', i: 'bottle' },
  { id: 'bag', t: 'Pack the backpack', i: 'backpack' },
  { id: 'shoes', t: 'Put on shoes', i: 'shoe' },
  { id: 'goodbye', t: 'Say goodbye and head out', i: 'door' },
];

const EVENING_EN = [
  { id: 'home', t: 'Get home', i: 'home' },
  { id: 'unpack', t: 'Unpack the backpack', i: 'backpack' },
  { id: 'homework', t: 'Homework', i: 'pencil' },
  { id: 'play', t: 'Play time', i: 'blocks' },
  { id: 'dinner', t: 'Dinner', i: 'dinner' },
  { id: 'bath', t: 'Shower or bath', i: 'shower' },
  { id: 'pajamas', t: 'Put on pajamas', i: 'pajama' },
  { id: 'teeth2', t: 'Brush teeth', i: 'tooth' },
  { id: 'tomorrow', t: "Lay out tomorrow's clothes", i: 'hanger' },
  { id: 'bagready', t: "Get tomorrow's bag ready", i: 'box' },
  { id: 'screenoff', t: 'Screens off', i: 'screenoff' },
  { id: 'story', t: 'Bedtime story', i: 'book' },
  { id: 'chat', t: 'A little chat about the day', i: 'chat' },
  { id: 'goodnight', t: 'Hug and goodnight', i: 'heart' },
  { id: 'sleep', t: 'Sleep', i: 'bed' },
];

const COURAGE_HE = ['אני יכול/ה!', 'יהיה לי יום טוב', 'אני מוכן/ה', 'אני אמיץ/ה', 'זה הולך להיות בסדר'];
const CALMING_HE = ['נשימות עמוקות', 'חיבוק', 'מוזיקה שקטה', 'קריאת ספר', 'שיחה קטנה'];
const COURAGE_EN = ["I can do this!", "I'm going to have a good day", "I'm ready", "I am brave", "It's going to be okay"];
const CALMING_EN = ['Deep breaths', 'A hug', 'Quiet music', 'Reading a book', 'A little chat'];

const STYLES_HE = [
  { id: 'soft', name: 'חם ורך', desc: 'צבעים חמים ומזמינים' },
  { id: 'quiet', name: 'נקי ושקט', desc: 'עיצוב מינימליסטי' },
  { id: 'grown', name: 'קצת יותר "גדול"', desc: 'עיצוב שמרגיש בוגר יותר' },
];
const STYLES_EN = [
  { id: 'soft', name: 'Warm and soft', desc: 'Warm, inviting colors' },
  { id: 'quiet', name: 'Clean and quiet', desc: 'A minimal design' },
  { id: 'grown', name: 'A bit more "grown up"', desc: 'A design that feels more mature' },
];

const FORMATS_HE = [
  { id: 'poster', name: 'לוח מלא', desc: 'כל השלבים במבט אחד, להדפסה ותלייה' },
  { id: 'checklist', name: 'רשימת סימון', desc: 'עם תיבות סימון לכל שלב' },
  { id: 'combined', name: 'בוקר וערב יחד', desc: 'שני הלוחות בדף אחד' },
  { id: 'separate', name: 'בוקר וערב בנפרד', desc: 'כל לוח בדף משלו' },
];
const FORMATS_EN = [
  { id: 'poster', name: 'Full board', desc: 'All the steps at a glance, ready to print and hang' },
  { id: 'checklist', name: 'Checklist', desc: 'With a checkbox for every step' },
  { id: 'combined', name: 'Morning and evening together', desc: 'Both boards on one page' },
  { id: 'separate', name: 'Morning and evening separately', desc: 'Each board on its own page' },
];

const INDEP_HE = [
  { id: 'self', t: 'לבד', i: 'self' },
  { id: 'together', t: 'ביחד', i: 'together' },
  { id: 'learning', t: 'לומדים', i: 'learning' },
];
const INDEP_EN = [
  { id: 'self', t: 'Alone', i: 'self' },
  { id: 'together', t: 'Together', i: 'together' },
  { id: 'learning', t: 'Learning', i: 'learning' },
];

export const MORNING_EVENING_CONTENT = {
  he: {
    MORNING: MORNING_HE, EVENING: EVENING_HE, COURAGE: COURAGE_HE, CALMING: CALMING_HE,
    STYLES: STYLES_HE, FORMATS: FORMATS_HE, INDEP: INDEP_HE,
    stepLabel: (n, total) => `שלב ${n} מתוך ${total}`,
    intro: {
      h1: 'לוח בוקר וערב אישי',
      lede: 'בנו יחד עם הילד/ה לוח שגרה שיעזור לו/לה לדעת בדיוק מה קורה בבוקר ובערב, בעצמאות ובביטחון.',
      band: ['לוקח כ-5 דקות', 'מתאים לכל המשפחה', 'להדפסה מיידית'],
      note: 'הלוח נוצר במכשיר שלכם בלבד ולא נשמר אצלנו, אלא אם תבחרו להשאיר אימייל בסוף.',
      card2Title: 'למה זה עוזר?',
      card2Text: 'לוח שגרה חזותי עוזר לילדים לדעת למה לצפות, לפעול בעצמאות רבה יותר, ומפחית ויכוחים על "מה עכשיו".',
      startBtn: 'בואו נתחיל ✨',
      resumeBtn: 'המשך מהיכן שהפסקתי',
      restartSmall: 'התחלה מחדש',
    },
    name: { h1: 'בשביל מי הלוח?', sub: 'כדי שנוכל להתאים אותו אישית.', label: 'שם הילד/ה', ph: 'איך קוראים לו/לה?', hint: 'אפשר להשאיר ריק ולהמשיך.' },
    pick: {
      kidPrompt: 'בואו נבחר ביחד עם הילד/ה!',
      morningH1: 'מה קורה אצלכם בבוקר?',
      eveningH1: 'מה קורה אצלכם בערב?',
      sub: 'בחרו את כל הפעולות שרלוונטיות, אפשר להוסיף פעולות משלכם בהמשך.',
      countLabel: (n) => `נבחרו ${n} פעולות. `,
      countLow: 'כדאי לבחור לפחות 3.',
      countHigh: 'זה הרבה שלבים, אולי כדאי לפשט מעט.',
    },
    order: {
      morningH1: 'באיזה סדר זה קורה?',
      morningSub: 'גררו כדי לסדר לפי הסדר הנכון.',
      eveningH1: 'באיזה סדר זה קורה בערב?',
      eveningSub: 'גררו כדי לסדר לפי הסדר הנכון.',
      kidPrompt: 'תנו לילד/ה לעזור לסדר!',
      addBtn: 'הוספת עוד פעולות',
      empty: 'לא נבחרו פעולות עדיין.',
      dragAria: 'גרירת ',
      upAria: 'הזזה למעלה',
      downAria: 'הזזה למטה',
      removeAria: 'הסרת ',
    },
    indep: {
      morningH1: 'מה עושה/ת לבד, ומה ביחד?',
      morningSub: 'זה עוזר לנו לדעת איפה לעודד עצמאות.',
      eveningH1: 'מה עושה/ת לבד בערב, ומה ביחד?',
      eveningSub: 'זה עוזר לנו לדעת איפה לעודד עצמאות.',
      kidPrompt: 'שאלו את הילד/ה מה הוא/היא מרגיש/ה מוכן/ה לעשות לבד.',
      goalTitle: 'יעד לעצמאות',
      goalHint: 'בחרו פעולה אחת שהילד/ה ינסה/תנסה לעשות לבד יותר.',
      flagAlone: 'לבד', flagTogether: 'ביחד', flagLearning: 'לומדים', flagGoal: 'יעד',
    },
    mExtra: {
      h1: 'עוד כמה פרטים לבוקר',
      sub: 'לא חובה למלא הכל.',
      startLabel: 'באיזו שעה מתחילים?', leaveLabel: 'באיזו שעה יוצאים מהבית?',
      songLabel: 'יש שיר שאתם שרים בבוקר?', songPh: 'לדוגמה: שיר הבוקר שלנו',
      sentenceTitle: 'משפט עידוד לבוקר', sentencePh: 'כתבו משפט משלכם',
    },
    bridge: {
      h1: 'עברנו לשגרת הערב',
      text: 'עכשיו נבנה את לוח הערב, בדיוק כמו שעשינו לבוקר.',
      cardTitle: 'למה זה שונה?',
      cardText: 'הערב הוא הזדמנות להירגע ולהתכונן למחר, השגרה יכולה להיות איטית ורגועה יותר.',
    },
    eExtra: {
      h1: 'עוד כמה פרטים לערב',
      sub: 'לא חובה למלא הכל.',
      startLabel: 'באיזו שעה מתחילים בערב?', bedLabel: 'באיזו שעה שינה?',
      calmTitle: 'פעילות מרגיעה לפני השינה', calmPh: 'כתבו פעילות משלכם',
      sentenceLabel: 'משפט לפני השינה', sentencePh: 'כתבו משפט משלכם',
    },
    style: { kidPrompt: 'תנו לילד/ה לבחור עיצוב!', h1: 'איזה עיצוב הכי מתאים?', sub: 'בחרו את הסגנון שהכי מדבר אליכם.' },
    format: { h1: 'איזה פורמט תרצו להדפיס?', sub: 'אפשר לבחור כמה, ולהדפיס את כולם ביחד.', hint: 'אפשר לשנות את זה מאוחר יותר.' },
    result: {
      h1Name: (n) => `הלוח של ${n} מוכן!`,
      h1Default: 'הלוח מוכן!',
      sub: 'הדפיסו ותלו במקום שהילד/ה רואה בקלות.',
      btnPrint: 'הדפסה', btnSave: 'שמירה כקובץ', btnEdit: 'עריכה', btnRestart: 'התחלה מחדש',
      howtoTitle: 'איך להשתמש בלוח',
      howtoText: 'תלו אותו במקום נגיש, עברו עליו ביחד כל בוקר וערב בהתחלה, ותנו לילד/ה לסמן שלבים בעצמו/ה כשאפשר.',
      ctaText: 'רוצים סיפור אישי שממשיך לתמוך בשגרה של הילד/ה שלכם?',
      ctaLink: 'ליצירת סיפור אישי ←',
      optinHint: 'רוצים לקבל את הלוח למייל, או לשמוע כשיהיו עוד פעילויות בחינם?',
      optinPh: 'האימייל שלך',
      optinSubmit: 'שליחה', optinSkip: 'לא תודה', optinThanks: 'תודה! נעדכן אתכם 💌',
    },
    nav: { back: '← חזרה', next: 'המשך', bridgeNext: 'המשך לשגרת הערב', formatNext: 'הצגת הלוח', resultBack: '← חזרה לעריכה' },
    validate: {
      name: 'נא למלא שם',
      mPick: 'בחרו לפחות 3 פעולות',
      ePick: 'בחרו לפחות 3 פעולות',
      format: 'בחרו לפחות פורמט אחד',
    },
    customAdder: {
      title: 'הוספת פעולה משלכם', ph: 'לדוגמה: להאכיל את הדג', addBtn: 'הוספה',
      hintMore: (n) => `ניתן להוסיף עוד ${n}.`, hintMax: 'הגעתם למקסימום הפעולות שניתן להוסיף.',
      deleteAria: 'מחיקת ',
    },
    sentenceOwn: 'משפט משלי',
    factLabels: { morning: ['שעת התחלה', 'שעת יציאה', 'שיר בוקר'], evening: ['שעת התחלה', 'שעת שינה', 'פעילות מרגיעה'] },
    goalPrefix: { morning: 'יעד לעצמאות בבוקר:', evening: 'יעד לעצמאות בערב:' },
    board: {
      sectionMorning: 'שגרת בוקר', sectionEvening: 'שגרת ערב',
      footTagline: 'לוח שגרה אישי',
      subChecklist: 'עם תיבות סימון', subPoster: 'לוח מלא',
      titleWithName: (name) => `הלוח של ${name}`, titleDefault: 'הלוח שלנו',
      morningTitleWithName: (name) => `הבוקר של ${name}`, morningTitleDefault: 'הבוקר שלנו',
      eveningTitleWithName: (name) => `הערב של ${name}`, eveningTitleDefault: 'הערב שלנו',
    },
    toast: { savefile: 'פותחים חלון הדפסה, בחרו "שמירה כ-PDF"', restartConfirm: 'לחצו שוב כדי לאשר איפוס' },
  },
  en: {
    MORNING: MORNING_EN, EVENING: EVENING_EN, COURAGE: COURAGE_EN, CALMING: CALMING_EN,
    STYLES: STYLES_EN, FORMATS: FORMATS_EN, INDEP: INDEP_EN,
    stepLabel: (n, total) => `Step ${n} of ${total}`,
    intro: {
      h1: 'A personal morning and evening board',
      lede: "Build a routine board together with your child, so they know exactly what happens in the morning and evening, with more independence and confidence.",
      band: ['Takes about 5 minutes', 'Works for the whole family', 'Print it right away'],
      note: 'The board is created only on your device and is not saved by us, unless you choose to leave an email at the end.',
      card2Title: 'Why does this help?',
      card2Text: 'A visual routine board helps kids know what to expect, act more independently, and reduces the "what now" arguments.',
      startBtn: "Let's start ✨",
      resumeBtn: 'Continue where I left off',
      restartSmall: 'Start over',
    },
    name: { h1: 'Who is this board for?', sub: 'So we can personalize it.', label: "Child's name", ph: "What's their name?", hint: 'You can leave this blank and continue.' },
    pick: {
      kidPrompt: 'Pick these together with your child!',
      morningH1: 'What happens at your house in the morning?',
      eveningH1: 'What happens at your house in the evening?',
      sub: 'Choose all the steps that apply, you can add your own steps later.',
      countLabel: (n) => `${n} steps selected. `,
      countLow: "It's a good idea to pick at least 3.",
      countHigh: "That's a lot of steps, you might want to simplify a bit.",
    },
    order: {
      morningH1: 'What order does this happen in?',
      morningSub: 'Drag to arrange them in the right order.',
      eveningH1: 'What order does this happen in the evening?',
      eveningSub: 'Drag to arrange them in the right order.',
      kidPrompt: 'Let your child help arrange these!',
      addBtn: 'Add more steps',
      empty: 'No steps selected yet.',
      dragAria: 'Drag ',
      upAria: 'Move up',
      downAria: 'Move down',
      removeAria: 'Remove ',
    },
    indep: {
      morningH1: 'What do they do alone, and what together?',
      morningSub: 'This helps us know where to encourage independence.',
      eveningH1: 'What do they do alone in the evening, and what together?',
      eveningSub: 'This helps us know where to encourage independence.',
      kidPrompt: 'Ask your child what they feel ready to do on their own.',
      goalTitle: 'Independence goal',
      goalHint: 'Choose one step your child will try to do more on their own.',
      flagAlone: 'Alone', flagTogether: 'Together', flagLearning: 'Learning', flagGoal: 'Goal',
    },
    mExtra: {
      h1: 'A few more morning details',
      sub: "You don't have to fill in everything.",
      startLabel: 'What time do you start?', leaveLabel: 'What time do you leave the house?',
      songLabel: 'Is there a song you sing in the morning?', songPh: 'For example: our morning song',
      sentenceTitle: 'A morning encouragement line', sentencePh: 'Write your own line',
    },
    bridge: {
      h1: "Now let's move to the evening routine",
      text: "Now we'll build the evening board, just like we did for the morning.",
      cardTitle: "Why is this different?",
      cardText: 'Evening is a chance to unwind and prepare for tomorrow, the routine can be slower and calmer.',
    },
    eExtra: {
      h1: 'A few more evening details',
      sub: "You don't have to fill in everything.",
      startLabel: 'What time do you start in the evening?', bedLabel: 'What time is bedtime?',
      calmTitle: 'A calming activity before bed', calmPh: 'Write your own activity',
      sentenceLabel: 'A bedtime line', sentencePh: 'Write your own line',
    },
    style: { kidPrompt: 'Let your child pick a design!', h1: 'Which design feels right?', sub: 'Pick the style that speaks to you most.' },
    format: { h1: 'Which format would you like to print?', sub: 'You can pick more than one, and print them all together.', hint: 'You can change this later.' },
    result: {
      h1Name: (n) => `${n}'s board is ready!`,
      h1Default: 'The board is ready!',
      sub: 'Print it and hang it somewhere your child can easily see.',
      btnPrint: 'Print', btnSave: 'Save as a file', btnEdit: 'Edit', btnRestart: 'Start over',
      howtoTitle: 'How to use this board',
      howtoText: "Hang it somewhere accessible, go over it together each morning and evening at first, and let your child check off steps themselves when they can.",
      ctaText: 'Want a personalized story that keeps supporting your child\u2019s routine?',
      ctaLink: 'Create a personal story ←',
      optinHint: 'Want the board emailed to you, or to hear when we release more free activities?',
      optinPh: 'Your email',
      optinSubmit: 'Send', optinSkip: 'No thanks', optinThanks: "Thank you! We'll be in touch 💌",
    },
    nav: { back: '← Back', next: 'Continue', bridgeNext: 'Continue to evening routine', formatNext: 'Show the board', resultBack: '← Back to edit' },
    validate: {
      name: 'Please enter a name',
      mPick: 'Choose at least 3 steps',
      ePick: 'Choose at least 3 steps',
      format: 'Choose at least one format',
    },
    customAdder: {
      title: 'Add your own step', ph: 'For example: Feed the fish', addBtn: 'Add',
      hintMore: (n) => `You can add ${n} more.`, hintMax: "You've reached the maximum number of steps you can add.",
      deleteAria: 'Remove ',
    },
    sentenceOwn: 'My own line',
    factLabels: { morning: ['Start time', 'Leaving time', 'Morning song'], evening: ['Start time', 'Bedtime', 'Calming activity'] },
    goalPrefix: { morning: 'Morning independence goal:', evening: 'Evening independence goal:' },
    board: {
      sectionMorning: 'Morning routine', sectionEvening: 'Evening routine',
      footTagline: 'Personal routine board',
      subChecklist: 'With checkboxes', subPoster: 'Full board',
      titleWithName: (name) => `${name}'s board`, titleDefault: 'Our board',
      morningTitleWithName: (name) => `${name}'s morning`, morningTitleDefault: 'Our morning',
      eveningTitleWithName: (name) => `${name}'s evening`, eveningTitleDefault: 'Our evening',
    },
    toast: { savefile: 'Opening the print window, choose "Save as PDF"', restartConfirm: 'Click again to confirm reset' },
  },
};